mode: crawel

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trade
    username: root
    password: gusdnd12
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true

  profiles:
    include: upbit